# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/EOS/project_flappy_screem/Flappy_SCREEEM/Project_flappy_screem/We_SCREEEEEEEM/We_SCREEEEEEEM.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0.xci
# IP: The module: 'design_1_axi_bram_ctrl_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/EOS/project_flappy_screem/Flappy_SCREEEM/Project_flappy_screem/We_SCREEEEEEEM/We_SCREEEEEEEM.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Xilinx/EOS/project_flappy_screem/Flappy_SCREEEM/Project_flappy_screem/We_SCREEEEEEEM/We_SCREEEEEEEM.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0.xci
# IP: The module: 'design_1_axi_bram_ctrl_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/EOS/project_flappy_screem/Flappy_SCREEEM/Project_flappy_screem/We_SCREEEEEEEM/We_SCREEEEEEEM.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
